// <auto-generated />
using System;
using System.Collections.Generic;
using CaixaMercado.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CaixaMercado.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MercadinhoDbContext))]
    [Migration("20260810173012_AddAtomicCheckoutCore")]
    partial class AddAtomicCheckoutCore
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("venda_numero_seq")
                .StartsAt(1001L);

            modelBuilder.Entity("CaixaMercado.Domain.Model.Auditoria.EventoAuditoria", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Acao")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("acao");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset>("CriadoEmUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em_utc");

                    b.Property<Guid>("OperadorId")
                        .HasColumnType("uuid")
                        .HasColumnName("operador_id");

                    b.Property<Guid>("RecursoId")
                        .HasColumnType("uuid")
                        .HasColumnName("recurso_id");

                    b.Property<Guid>("SessaoCaixaId")
                        .HasColumnType("uuid")
                        .HasColumnName("sessao_caixa_id");

                    b.Property<Guid>("TerminalId")
                        .HasColumnType("uuid")
                        .HasColumnName("terminal_id");

                    b.HasKey("Id")
                        .HasName("pk_eventos_auditoria");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("ix_eventos_auditoria_correlation_id")
                        .HasFilter("correlation_id IS NOT NULL");

                    b.HasIndex("SessaoCaixaId");

                    b.HasIndex("Acao", "RecursoId")
                        .HasDatabaseName("ix_eventos_auditoria_acao_recurso");

                    b.HasIndex("TerminalId", "CriadoEmUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_eventos_auditoria_terminal_criado_em");

                    b.ToTable("eventos_auditoria", (string)null);
                });

            modelBuilder.Entity("CaixaMercado.Domain.Model.Caixas.MovimentoCaixa", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CriadoEmUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em_utc");

                    b.Property<short>("Forma")
                        .HasColumnType("smallint")
                        .HasColumnName("forma");

                    b.Property<Guid>("PagamentoId")
                        .HasColumnType("uuid")
                        .HasColumnName("pagamento_id");

                    b.Property<Guid>("SessaoCaixaId")
                        .HasColumnType("uuid")
                        .HasColumnName("sessao_caixa_id");

                    b.Property<decimal>("Troco")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("troco");

                    b.Property<decimal>("ValorLiquido")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor_liquido");

                    b.Property<decimal>("ValorRecebido")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor_recebido");

                    b.Property<Guid>("VendaId")
                        .HasColumnType("uuid")
                        .HasColumnName("venda_id");

                    b.HasKey("Id")
                        .HasName("pk_caixa_movimentos");

                    b.HasIndex("PagamentoId")
                        .IsUnique()
                        .HasDatabaseName("ux_caixa_movimentos_pagamento");

                    b.HasIndex("VendaId")
                        .HasDatabaseName("ix_caixa_movimentos_venda");

                    b.HasIndex("SessaoCaixaId", "CriadoEmUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_caixa_movimentos_sessao_criado_em");

                    b.ToTable("caixa_movimentos", null, t =>
                        {
                            t.HasCheckConstraint("ck_caixa_movimentos_forma", "forma BETWEEN 1 AND 5");

                            t.HasCheckConstraint("ck_caixa_movimentos_valores", "valor_liquido > 0 AND valor_recebido >= valor_liquido AND troco = valor_recebido - valor_liquido");
                        });
                });

            modelBuilder.Entity("CaixaMercado.Domain.Model.Caixas.SessaoCaixa", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AbertaEmUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("aberta_em_utc");

                    b.Property<DateTimeOffset?>("FechadaEmUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fechada_em_utc");

                    b.Property<Guid>("FilialId")
                        .HasColumnType("uuid")
                        .HasColumnName("filial_id");

                    b.Property<Guid>("OperadorAberturaId")
                        .HasColumnType("uuid")
                        .HasColumnName("operador_abertura_id");

                    b.Property<Guid?>("OperadorFechamentoId")
                        .HasColumnType("uuid")
                        .HasColumnName("operador_fechamento_id");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<Guid>("TerminalId")
                        .HasColumnType("uuid")
                        .HasColumnName("terminal_id");

                    b.Property<decimal>("ValorAbertura")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor_abertura");

                    b.Property<decimal?>("ValorContadoFechamento")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor_contado_fechamento");

                    b.Property<decimal?>("ValorEsperadoFechamento")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor_esperado_fechamento");

                    b.Property<long>("Versao")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("versao");

                    b.HasKey("Id")
                        .HasName("pk_sessoes_caixa");

                    b.HasIndex("TerminalId")
                        .IsUnique()
                        .HasDatabaseName("ux_sessoes_caixa_terminal_aberta")
                        .HasFilter("status = 1");

                    b.HasIndex("FilialId", "AbertaEmUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_sessoes_caixa_filial_aberta_em");

                    b.ToTable("sessoes_caixa", null, t =>
                        {
                            t.HasCheckConstraint("ck_sessoes_caixa_fechamento", "(status = 1 AND operador_fechamento_id IS NULL AND valor_esperado_fechamento IS NULL AND valor_contado_fechamento IS NULL AND fechada_em_utc IS NULL) OR (status = 2 AND operador_fechamento_id IS NOT NULL AND valor_esperado_fechamento IS NOT NULL AND valor_contado_fechamento IS NOT NULL AND fechada_em_utc IS NOT NULL)");

                            t.HasCheckConstraint("ck_sessoes_caixa_status", "status IN (1, 2)");

                            t.HasCheckConstraint("ck_sessoes_caixa_valor_abertura", "valor_abertura >= 0");

                            t.HasCheckConstraint("ck_sessoes_caixa_valor_contado", "valor_contado_fechamento IS NULL OR valor_contado_fechamento >= 0");

                            t.HasCheckConstraint("ck_sessoes_caixa_valor_esperado", "valor_esperado_fechamento IS NULL OR valor_esperado_fechamento >= 0");

                            t.HasCheckConstraint("ck_sessoes_caixa_versao", "versao >= 0");
                        });
                });

            modelBuilder.Entity("CaixaMercado.Domain.Model.Catalogo.Produto", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<string>("CodigoInterno")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("codigo_interno");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("descricao");

                    b.Property<string>("Ean")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("ean");

                    b.Property<string>("Plu")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("plu");

                    b.Property<decimal>("PrecoVenda")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("preco_venda");

                    b.Property<bool>("ProdutoPesavel")
                        .HasColumnType("boolean")
                        .HasColumnName("produto_pesavel");

                    b.Property<short>("UnidadeMedida")
                        .HasColumnType("smallint")
                        .HasColumnName("unidade_medida");

                    b.HasKey("Id")
                        .HasName("pk_produtos");

                    b.HasIndex("CodigoInterno")
                        .IsUnique()
                        .HasDatabaseName("ux_produtos_codigo_interno");

                    b.HasIndex("Ean")
                        .IsUnique()
                        .HasDatabaseName("ux_produtos_ean")
                        .HasFilter("ean IS NOT NULL");

                    b.HasIndex("Plu")
                        .IsUnique()
                        .HasDatabaseName("ux_produtos_plu")
                        .HasFilter("plu IS NOT NULL");

                    b.HasIndex("Ativo", "Descricao")
                        .HasDatabaseName("ix_produtos_ativo_descricao");

                    b.ToTable("produtos", null, t =>
                        {
                            t.HasCheckConstraint("ck_produtos_pesavel_unidade", "NOT produto_pesavel OR unidade_medida = 2");

                            t.HasCheckConstraint("ck_produtos_preco_venda", "preco_venda >= 0");

                            t.HasCheckConstraint("ck_produtos_unidade_medida", "unidade_medida IN (1, 2)");
                        });
                });

            modelBuilder.Entity("CaixaMercado.Domain.Model.Estoque.MovimentoEstoque", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CriadoEmUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em_utc");

                    b.Property<Guid?>("ItemVendaId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_venda_id");

                    b.Property<Guid>("ProdutoId")
                        .HasColumnType("uuid")
                        .HasColumnName("produto_id");

                    b.Property<decimal>("Quantidade")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("quantidade");

                    b.Property<short>("Tipo")
                        .HasColumnType("smallint")
                        .HasColumnName("tipo");

                    b.Property<Guid?>("VendaId")
                        .HasColumnType("uuid")
                        .HasColumnName("venda_id");

                    b.HasKey("Id")
                        .HasName("pk_estoque_movimentos");

                    b.HasIndex("VendaId")
                        .HasDatabaseName("ix_estoque_movimentos_venda");

                    b.HasIndex("ItemVendaId", "Tipo")
                        .IsUnique()
                        .HasDatabaseName("ux_estoque_movimentos_item_tipo")
                        .HasFilter("item_venda_id IS NOT NULL");

                    b.HasIndex("ProdutoId", "CriadoEmUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_estoque_movimentos_produto_criado_em");

                    b.ToTable("estoque_movimentos", null, t =>
                        {
                            t.HasCheckConstraint("ck_estoque_movimentos_quantidade", "quantidade > 0");

                            t.HasCheckConstraint("ck_estoque_movimentos_tipo", "tipo BETWEEN 1 AND 4");
                        });
                });

            modelBuilder.Entity("CaixaMercado.Domain.Model.Vendas.ItemVenda", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Desconto")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("desconto");

                    b.Property<decimal>("Quantidade")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("quantidade");

                    b.Property<int>("Sequencial")
                        .HasColumnType("integer")
                        .HasColumnName("sequencial");

                    b.Property<Guid>("venda_id")
                        .HasColumnType("uuid")
                        .HasColumnName("venda_id");

                    b.ComplexProperty<Dictionary<string, object>>("Produto", "CaixaMercado.Domain.Model.Vendas.ItemVenda.Produto#ProdutoSnapshot", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("CodigoInterno")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)")
                                .HasColumnName("produto_codigo_interno");

                            b1.Property<string>("Descricao")
                                .IsRequired()
                                .HasMaxLength(160)
                                .HasColumnType("character varying(160)")
                                .HasColumnName("produto_descricao");

                            b1.Property<string>("Ean")
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)")
                                .HasColumnName("produto_ean");

                            b1.Property<string>("Plu")
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)")
                                .HasColumnName("produto_plu");

                            b1.Property<decimal>("PrecoUnitario")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("produto_preco_unitario");

                            b1.Property<Guid>("ProdutoId")
                                .HasColumnType("uuid")
                                .HasColumnName("produto_id");

                            b1.Property<short>("UnidadeMedida")
                                .HasColumnType("smallint")
                                .HasColumnName("produto_unidade_medida");
                        });

                    b.HasKey("Id")
                        .HasName("pk_venda_itens");

                    b.HasIndex("venda_id", "Sequencial")
                        .IsUnique()
                        .HasDatabaseName("ux_venda_itens_venda_sequencial");

                    b.ToTable("venda_itens", null, t =>
                        {
                            t.HasCheckConstraint("ck_venda_itens_desconto", "desconto >= 0");

                            t.HasCheckConstraint("ck_venda_itens_preco_unitario", "produto_preco_unitario >= 0");

                            t.HasCheckConstraint("ck_venda_itens_quantidade", "quantidade > 0");

                            t.HasCheckConstraint("ck_venda_itens_sequencial", "sequencial > 0");

                            t.HasCheckConstraint("ck_venda_itens_unidade_medida", "produto_unidade_medida IN (1, 2)");
                        });
                });

            modelBuilder.Entity("CaixaMercado.Domain.Model.Vendas.PagamentoVenda", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<short>("Forma")
                        .HasColumnType("smallint")
                        .HasColumnName("forma");

                    b.Property<string>("ReferenciaExterna")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("referencia_externa");

                    b.Property<DateTimeOffset>("RegistradoEmUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registrado_em_utc");

                    b.Property<Guid>("SessaoCaixaId")
                        .HasColumnType("uuid")
                        .HasColumnName("sessao_caixa_id");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<decimal>("ValorAplicado")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor_aplicado");

                    b.Property<decimal?>("ValorRecebidoDinheiro")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor_recebido_dinheiro");

                    b.Property<Guid>("VendaId")
                        .HasColumnType("uuid")
                        .HasColumnName("venda_id");

                    b.HasKey("Id")
                        .HasName("pk_venda_pagamentos");

                    b.HasIndex("ReferenciaExterna")
                        .HasDatabaseName("ix_venda_pagamentos_referencia_externa")
                        .HasFilter("referencia_externa IS NOT NULL");

                    b.HasIndex("SessaoCaixaId")
                        .HasDatabaseName("ix_venda_pagamentos_sessao");

                    b.HasIndex("VendaId")
                        .HasDatabaseName("ix_venda_pagamentos_venda");

                    b.ToTable("venda_pagamentos", null, t =>
                        {
                            t.HasCheckConstraint("ck_venda_pagamentos_aprovacao_eletronica", "forma = 1 OR status <> 2 OR referencia_externa IS NOT NULL");

                            t.HasCheckConstraint("ck_venda_pagamentos_dinheiro", "(forma = 1 AND valor_recebido_dinheiro IS NOT NULL AND valor_recebido_dinheiro >= valor_aplicado) OR (forma <> 1 AND valor_recebido_dinheiro IS NULL)");

                            t.HasCheckConstraint("ck_venda_pagamentos_forma", "forma BETWEEN 1 AND 5");

                            t.HasCheckConstraint("ck_venda_pagamentos_status", "status BETWEEN 1 AND 5");

                            t.HasCheckConstraint("ck_venda_pagamentos_valor", "valor_aplicado > 0");
                        });
                });

            modelBuilder.Entity("CaixaMercado.Domain.Model.Vendas.Venda", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CriadaEmUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criada_em_utc");

                    b.Property<decimal>("Desconto")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("desconto");

                    b.Property<Guid>("FilialId")
                        .HasColumnType("uuid")
                        .HasColumnName("filial_id");

                    b.Property<long?>("Numero")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("numero")
                        .HasDefaultValueSql("nextval('venda_numero_seq')");

                    b.Property<Guid>("OperadorId")
                        .HasColumnType("uuid")
                        .HasColumnName("operador_id");

                    b.Property<Guid>("SessaoCaixaId")
                        .HasColumnType("uuid")
                        .HasColumnName("sessao_caixa_id");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<Guid>("TerminalId")
                        .HasColumnType("uuid")
                        .HasColumnName("terminal_id");

                    b.Property<long>("Versao")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("versao");

                    b.HasKey("Id")
                        .HasName("pk_vendas");

                    b.HasIndex("FilialId", "Numero")
                        .IsUnique()
                        .HasDatabaseName("ux_vendas_filial_numero")
                        .HasFilter("numero IS NOT NULL");

                    b.HasIndex("OperadorId", "CriadaEmUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_vendas_operador_criada_em");

                    b.HasIndex("TerminalId", "CriadaEmUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_vendas_terminal_criada_em");

                    b.HasIndex("FilialId", "Status", "CriadaEmUtc")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("ix_vendas_filial_status_criada_em");

                    b.ToTable("vendas", null, t =>
                        {
                            t.HasCheckConstraint("ck_vendas_desconto", "desconto >= 0");

                            t.HasCheckConstraint("ck_vendas_numero", "numero IS NULL OR numero > 0");

                            t.HasCheckConstraint("ck_vendas_status", "status BETWEEN 1 AND 8");

                            t.HasCheckConstraint("ck_vendas_versao", "versao >= 0");
                        });
                });

            modelBuilder.Entity("CaixaMercado.Infrastructure.Persistence.RegistroIdempotenciaEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Chave")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("chave");

                    b.Property<short>("CodigoResultado")
                        .HasColumnType("smallint")
                        .HasColumnName("codigo_resultado");

                    b.Property<DateTimeOffset>("CriadoEmUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em_utc");

                    b.Property<string>("HashRequisicao")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("hash_requisicao");

                    b.Property<string>("Mensagem")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("mensagem");

                    b.Property<string>("Operacao")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("operacao");

                    b.Property<string>("RecursoJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("recurso_json");

                    b.Property<Guid>("TerminalId")
                        .HasColumnType("uuid")
                        .HasColumnName("terminal_id");

                    b.HasKey("Id")
                        .HasName("pk_requisicoes_idempotentes");

                    b.HasIndex("CriadoEmUtc")
                        .HasDatabaseName("ix_requisicoes_idempotentes_criado_em");

                    b.HasIndex("TerminalId", "Chave")
                        .IsUnique()
                        .HasDatabaseName("ux_requisicoes_idempotentes_terminal_chave");

                    b.ToTable("requisicoes_idempotentes", null, t =>
                        {
                            t.HasCheckConstraint("ck_requisicoes_idempotentes_codigo", "codigo_resultado BETWEEN 0 AND 8");

                            t.HasCheckConstraint("ck_requisicoes_idempotentes_hash", "char_length(hash_requisicao) = 64");
                        });
                });

            modelBuilder.Entity("CaixaMercado.Infrastructure.Persistence.SaldoEstoqueEntity", b =>
                {
                    b.Property<Guid>("ProdutoId")
                        .HasColumnType("uuid")
                        .HasColumnName("produto_id");

                    b.Property<decimal>("Quantidade")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("quantidade");

                    b.Property<long>("Versao")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("versao");

                    b.HasKey("ProdutoId")
                        .HasName("pk_estoque_saldos");

                    b.ToTable("estoque_saldos", null, t =>
                        {
                            t.HasCheckConstraint("ck_estoque_saldos_quantidade", "quantidade >= 0");

                            t.HasCheckConstraint("ck_estoque_saldos_versao", "versao >= 0");
                        });
                });

            modelBuilder.Entity("CaixaMercado.Domain.Model.Auditoria.EventoAuditoria", b =>
                {
                    b.HasOne("CaixaMercado.Domain.Model.Caixas.SessaoCaixa", null)
                        .WithMany()
                        .HasForeignKey("SessaoCaixaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_eventos_auditoria_sessoes_caixa_sessao_id");
                });

            modelBuilder.Entity("CaixaMercado.Domain.Model.Caixas.MovimentoCaixa", b =>
                {
                    b.HasOne("CaixaMercado.Domain.Model.Vendas.PagamentoVenda", null)
                        .WithOne()
                        .HasForeignKey("CaixaMercado.Domain.Model.Caixas.MovimentoCaixa", "PagamentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_caixa_movimentos_venda_pagamentos_pagamento_id");

                    b.HasOne("CaixaMercado.Domain.Model.Caixas.SessaoCaixa", null)
                        .WithMany()
                        .HasForeignKey("SessaoCaixaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_caixa_movimentos_sessoes_caixa_sessao_id");

                    b.HasOne("CaixaMercado.Domain.Model.Vendas.Venda", null)
                        .WithMany()
                        .HasForeignKey("VendaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_caixa_movimentos_vendas_venda_id");
                });

            modelBuilder.Entity("CaixaMercado.Domain.Model.Estoque.MovimentoEstoque", b =>
                {
                    b.HasOne("CaixaMercado.Domain.Model.Vendas.ItemVenda", null)
                        .WithMany()
                        .HasForeignKey("ItemVendaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_estoque_movimentos_venda_itens_item_venda_id");

                    b.HasOne("CaixaMercado.Domain.Model.Catalogo.Produto", null)
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_estoque_movimentos_produtos_produto_id");

                    b.HasOne("CaixaMercado.Domain.Model.Vendas.Venda", null)
                        .WithMany()
                        .HasForeignKey("VendaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_estoque_movimentos_vendas_venda_id");
                });

            modelBuilder.Entity("CaixaMercado.Domain.Model.Vendas.ItemVenda", b =>
                {
                    b.HasOne("CaixaMercado.Domain.Model.Vendas.Venda", null)
                        .WithMany("Itens")
                        .HasForeignKey("venda_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CaixaMercado.Domain.Model.Vendas.PagamentoVenda", b =>
                {
                    b.HasOne("CaixaMercado.Domain.Model.Caixas.SessaoCaixa", null)
                        .WithMany()
                        .HasForeignKey("SessaoCaixaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_venda_pagamentos_sessoes_caixa_sessao_id");

                    b.HasOne("CaixaMercado.Domain.Model.Vendas.Venda", null)
                        .WithMany()
                        .HasForeignKey("VendaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_venda_pagamentos_vendas_venda_id");
                });

            modelBuilder.Entity("CaixaMercado.Infrastructure.Persistence.SaldoEstoqueEntity", b =>
                {
                    b.HasOne("CaixaMercado.Domain.Model.Catalogo.Produto", null)
                        .WithOne()
                        .HasForeignKey("CaixaMercado.Infrastructure.Persistence.SaldoEstoqueEntity", "ProdutoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_estoque_saldos_produtos_produto_id");
                });

            modelBuilder.Entity("CaixaMercado.Domain.Model.Vendas.Venda", b =>
                {
                    b.Navigation("Itens");
                });
#pragma warning restore 612, 618
        }
    }
}
