// <auto-generated />
using System;
using System.Collections.Generic;
using CaixaMercado.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CaixaMercado.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MercadinhoDbContext))]
    partial class MercadinhoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("venda_numero_seq")
                .StartsAt(1001L);

            modelBuilder.Entity("CaixaMercado.Domain.Model.Catalogo.Produto", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<string>("CodigoInterno")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("codigo_interno");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("descricao");

                    b.Property<string>("Ean")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("ean");

                    b.Property<string>("Plu")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("plu");

                    b.Property<decimal>("PrecoVenda")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("preco_venda");

                    b.Property<bool>("ProdutoPesavel")
                        .HasColumnType("boolean")
                        .HasColumnName("produto_pesavel");

                    b.Property<short>("UnidadeMedida")
                        .HasColumnType("smallint")
                        .HasColumnName("unidade_medida");

                    b.HasKey("Id")
                        .HasName("pk_produtos");

                    b.HasIndex("CodigoInterno")
                        .IsUnique()
                        .HasDatabaseName("ux_produtos_codigo_interno");

                    b.HasIndex("Ean")
                        .IsUnique()
                        .HasDatabaseName("ux_produtos_ean")
                        .HasFilter("ean IS NOT NULL");

                    b.HasIndex("Plu")
                        .IsUnique()
                        .HasDatabaseName("ux_produtos_plu")
                        .HasFilter("plu IS NOT NULL");

                    b.HasIndex("Ativo", "Descricao")
                        .HasDatabaseName("ix_produtos_ativo_descricao");

                    b.ToTable("produtos", null, t =>
                        {
                            t.HasCheckConstraint("ck_produtos_pesavel_unidade", "NOT produto_pesavel OR unidade_medida = 2");

                            t.HasCheckConstraint("ck_produtos_preco_venda", "preco_venda >= 0");

                            t.HasCheckConstraint("ck_produtos_unidade_medida", "unidade_medida IN (1, 2)");
                        });
                });

            modelBuilder.Entity("CaixaMercado.Domain.Model.Vendas.ItemVenda", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Desconto")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("desconto");

                    b.Property<decimal>("Quantidade")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("quantidade");

                    b.Property<int>("Sequencial")
                        .HasColumnType("integer")
                        .HasColumnName("sequencial");

                    b.Property<Guid>("venda_id")
                        .HasColumnType("uuid")
                        .HasColumnName("venda_id");

                    b.ComplexProperty<Dictionary<string, object>>("Produto", "CaixaMercado.Domain.Model.Vendas.ItemVenda.Produto#ProdutoSnapshot", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("CodigoInterno")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)")
                                .HasColumnName("produto_codigo_interno");

                            b1.Property<string>("Descricao")
                                .IsRequired()
                                .HasMaxLength(160)
                                .HasColumnType("character varying(160)")
                                .HasColumnName("produto_descricao");

                            b1.Property<string>("Ean")
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)")
                                .HasColumnName("produto_ean");

                            b1.Property<string>("Plu")
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)")
                                .HasColumnName("produto_plu");

                            b1.Property<decimal>("PrecoUnitario")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("produto_preco_unitario");

                            b1.Property<Guid>("ProdutoId")
                                .HasColumnType("uuid")
                                .HasColumnName("produto_id");

                            b1.Property<short>("UnidadeMedida")
                                .HasColumnType("smallint")
                                .HasColumnName("produto_unidade_medida");
                        });

                    b.HasKey("Id")
                        .HasName("pk_venda_itens");

                    b.HasIndex("venda_id", "Sequencial")
                        .IsUnique()
                        .HasDatabaseName("ux_venda_itens_venda_sequencial");

                    b.ToTable("venda_itens", null, t =>
                        {
                            t.HasCheckConstraint("ck_venda_itens_desconto", "desconto >= 0");

                            t.HasCheckConstraint("ck_venda_itens_preco_unitario", "produto_preco_unitario >= 0");

                            t.HasCheckConstraint("ck_venda_itens_quantidade", "quantidade > 0");

                            t.HasCheckConstraint("ck_venda_itens_sequencial", "sequencial > 0");

                            t.HasCheckConstraint("ck_venda_itens_unidade_medida", "produto_unidade_medida IN (1, 2)");
                        });
                });

            modelBuilder.Entity("CaixaMercado.Domain.Model.Vendas.Venda", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CriadaEmUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criada_em_utc");

                    b.Property<decimal>("Desconto")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("desconto");

                    b.Property<Guid>("FilialId")
                        .HasColumnType("uuid")
                        .HasColumnName("filial_id");

                    b.Property<long?>("Numero")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("numero")
                        .HasDefaultValueSql("nextval('venda_numero_seq')");

                    b.Property<Guid>("OperadorId")
                        .HasColumnType("uuid")
                        .HasColumnName("operador_id");

                    b.Property<Guid>("SessaoCaixaId")
                        .HasColumnType("uuid")
                        .HasColumnName("sessao_caixa_id");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<Guid>("TerminalId")
                        .HasColumnType("uuid")
                        .HasColumnName("terminal_id");

                    b.Property<long>("Versao")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("versao");

                    b.HasKey("Id")
                        .HasName("pk_vendas");

                    b.HasIndex("FilialId", "Numero")
                        .IsUnique()
                        .HasDatabaseName("ux_vendas_filial_numero")
                        .HasFilter("numero IS NOT NULL");

                    b.HasIndex("OperadorId", "CriadaEmUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_vendas_operador_criada_em");

                    b.HasIndex("TerminalId", "CriadaEmUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_vendas_terminal_criada_em");

                    b.HasIndex("FilialId", "Status", "CriadaEmUtc")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("ix_vendas_filial_status_criada_em");

                    b.ToTable("vendas", null, t =>
                        {
                            t.HasCheckConstraint("ck_vendas_desconto", "desconto >= 0");

                            t.HasCheckConstraint("ck_vendas_numero", "numero IS NULL OR numero > 0");

                            t.HasCheckConstraint("ck_vendas_status", "status BETWEEN 1 AND 8");

                            t.HasCheckConstraint("ck_vendas_versao", "versao >= 0");
                        });
                });

            modelBuilder.Entity("CaixaMercado.Domain.Model.Vendas.ItemVenda", b =>
                {
                    b.HasOne("CaixaMercado.Domain.Model.Vendas.Venda", null)
                        .WithMany("Itens")
                        .HasForeignKey("venda_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CaixaMercado.Domain.Model.Vendas.Venda", b =>
                {
                    b.Navigation("Itens");
                });
#pragma warning restore 612, 618
        }
    }
}
